# Generated by Django 5.1 on 2024-08-27 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('user_department', models.IntegerField(verbose_name='Department')),
                ('user_position', models.IntegerField(verbose_name='Position')),
                ('user_date_added', models.DateField(default=datetime.datetime(2024, 8, 27, 11, 6, 44, 398204, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
