# Generated by Django 5.1 on 2024-08-27 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 11, 19, 43, 791430, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_department',
            field=models.CharField(choices=[('IT', 'IT'), ('Engineering', 'Engineering')], max_length=200, verbose_name='Department'),
        ),
    ]
