# Generated by Django 5.1 on 2024-08-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=200, verbose_name='Position Name')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 11, 27, 37, 654182, tzinfo=datetime.timezone.utc)),
        ),
    ]
