# Generated by Django 5.1 on 2024-08-27 11:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_position_alter_user_user_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 11, 38, 6, 692759, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.position', verbose_name='Position'),
        ),
    ]
