# Generated by Django 5.1 on 2024-08-27 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_date_added_alter_user_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 11, 39, 17, 412813, tzinfo=datetime.timezone.utc)),
        ),
    ]
