# Generated by Django 5.1 on 2024-08-27 13:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_user_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200, verbose_name='Department Name')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 13, 8, 19, 605930, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Department'),
        ),
    ]
