# Generated by Django 5.1 on 2024-09-15 06:03

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_department_alter_user_user_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='user_image/user_default_image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 15, 6, 3, 38, 901767, tzinfo=datetime.timezone.utc)),
        ),
    ]
