# Generated by Django 5.1 on 2024-09-15 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_user_image_alter_user_user_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_date_added',
            field=models.DateField(default=datetime.datetime(2024, 9, 15, 6, 29, 53, 672222, tzinfo=datetime.timezone.utc)),
        ),
    ]
